### ISSUE TITLE
SBF file not parsed but handled in sbfAnalyzer

### ISSUE THREAD

**Issue by fkaiser** [marcojob/pysbf#2]
When running through inop .sbf files saw that for some .sbf files parser returns empty. However with sbfAnalyzer one sees that file actually could be parsed. It seems as it fails at function fread(body_ptr, body_length, 1, f) in sbf.pyx.

In the list below the ones with "N/A" had that problem: **redacted screenshot for confidentiality**

**Comment by marcojob** [comment]
Probably related to this: Sometimes the main parsing loop fails silently, unsure what happens there.

**Comment by marcojob** [comment]
Happened again with file where 700 ext. events are expected, but none are parsed. Can't upload since file is too large.
